begin
   EXECUTE IMMEDIATE 'DROP TABLE Loans';
   EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE Customers';
   EXCEPTION WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE Customers ( CustomerID NUMBER PRIMARY KEY, Name VARCHAR2(100), DOB DATE);

CREATE TABLE Loans ( LoanID NUMBER PRIMARY KEY, CustomerID NUMBER, LoanAmount NUMBER, InterestRate NUMBER, StartDate DATE, EndDate DATE, FOREIGN KEY (CustomerID) REFERENCES Customers(CustomerID));
INSERT INTO Customers VALUES (1, 'Ram', TO_DATE('1998-10-15', 'YYYY-MM-DD'));
INSERT INTO Customers VALUES (2, 'Jayanth', TO_DATE('1980-11-20', 'YYYY-MM-DD'));
INSERT INTO Customers VALUES (3, 'Sita', TO_DATE('1997-04-01', 'YYYY-MM-DD'));
INSERT INTO Loans VALUES (1, 1, 5000, 8, TO_DATE('2021-04-01', 'YYYY-MM-DD'), TO_DATE('2025-07-10', 'YYYY-MM-DD'));
INSERT INTO Loans VALUES (2, 2, 4000, 7, TO_DATE('2021-05-01', 'YYYY-MM-DD'), TO_DATE('2025-07-15', 'YYYY-MM-DD'));
INSERT INTO Loans VALUES (3, 3, 6000, 9, TO_DATE('2021-06-01', 'YYYY-MM-DD'), TO_DATE('2025-07-20', 'YYYY-MM-DD'));
COMMIT;
BEGIN
FOR rec IN (
    SELECT l.LoanID, c.DOB
    FROM Customers c
    JOIN Loans l ON c.CustomerID = l.CustomerID
) 
LOOP
    IF FLOOR(MONTHS_BETWEEN(SYSDATE, rec.DOB) / 12) > 60 THEN
        UPDATE Loans
        SET InterestRate = InterestRate - 1
        WHERE LoanID = rec.LoanID;
    END IF;
END LOOP;
COMMIT;
END;
/
SELECT * FROM Loans;
